"""Add family assistance history

Revision ID: 38a7c51b705a
Revises: 9dbe65c714a8
Create Date: 2026-04-08 17:44:52.000489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38a7c51b705a'
down_revision: Union[str, None] = '9dbe65c714a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_assistance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('assistance_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_provided', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('professional_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_assistance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_assistance_id'), ['id'], unique=False)

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendances_id'), ['id'], unique=False)

    with op.batch_alter_table('child_medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_medications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_child_medications_med_name'), ['med_name'], unique=False)

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_children_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_children_name'), ['name'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_id'), ['id'], unique=False)

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('families_cpf_hash_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_families_cpf'), ['cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_families_cpf_hash'), ['cpf_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_families_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_families_name_responsible'), ['name_responsible'], unique=False)
        batch_op.create_index(batch_op.f('ix_families_neighborhood'), ['neighborhood'], unique=False)
        batch_op.create_index(batch_op.f('ix_families_rg_hash'), ['rg_hash'], unique=False)

    with op.batch_alter_table('multidisciplinary_evolutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_multidisciplinary_evolutions_id'), ['id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('professionals_cpf_hash_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('professionals_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_professionals_cpf'), ['cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_professionals_cpf_hash'), ['cpf_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_professionals_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_professionals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_professionals_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_professionals_rg_hash'), ['rg_hash'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)

    with op.batch_alter_table('resource_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_sources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_sources_name'), ['name'], unique=False)

    with op.batch_alter_table('revenues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revenues_id'), ['id'], unique=False)

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_name'))
        batch_op.drop_index(batch_op.f('ix_wallets_id'))

    with op.batch_alter_table('revenues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revenues_id'))

    with op.batch_alter_table('resource_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_sources_name'))
        batch_op.drop_index(batch_op.f('ix_resource_sources_id'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professionals_rg_hash'))
        batch_op.drop_index(batch_op.f('ix_professionals_name'))
        batch_op.drop_index(batch_op.f('ix_professionals_id'))
        batch_op.drop_index(batch_op.f('ix_professionals_email'))
        batch_op.drop_index(batch_op.f('ix_professionals_cpf_hash'))
        batch_op.drop_index(batch_op.f('ix_professionals_cpf'))
        batch_op.create_unique_constraint(batch_op.f('professionals_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('professionals_cpf_hash_key'), ['cpf_hash'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    with op.batch_alter_table('multidisciplinary_evolutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_multidisciplinary_evolutions_id'))

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_families_rg_hash'))
        batch_op.drop_index(batch_op.f('ix_families_neighborhood'))
        batch_op.drop_index(batch_op.f('ix_families_name_responsible'))
        batch_op.drop_index(batch_op.f('ix_families_id'))
        batch_op.drop_index(batch_op.f('ix_families_cpf_hash'))
        batch_op.drop_index(batch_op.f('ix_families_cpf'))
        batch_op.create_unique_constraint(batch_op.f('families_cpf_hash_key'), ['cpf_hash'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_id'))

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_children_name'))
        batch_op.drop_index(batch_op.f('ix_children_id'))
        batch_op.alter_column('birth_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('child_medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_medications_med_name'))
        batch_op.drop_index(batch_op.f('ix_child_medications_id'))

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_id'))

    with op.batch_alter_table('family_assistance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_assistance_id'))

    op.drop_table('family_assistance')
    # ### end Alembic commands ###
