"""schema_sync_v2

Revision ID: 9dbe65c714a8
Revises: 
Create Date: 2026-02-25 20:59:55.392759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dbe65c714a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('spendings', sa.Float(), nullable=True),
    sa.Column('hours_spent', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_expenses_attendance_id', 'attendances', ['attendance_id'], ['id'])

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rg_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cpf_hash', sa.String(), nullable=True))
        batch_op.drop_index('ix_families_cpf')
        batch_op.create_index(batch_op.f('ix_families_cpf'), ['cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_families_cpf_hash'), ['cpf_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_families_rg_hash'), ['rg_hash'], unique=False)

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rg_hash', sa.String(), nullable=True))
        batch_op.drop_index('ix_professionals_cpf')
        batch_op.create_index(batch_op.f('ix_professionals_cpf'), ['cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_professionals_cpf_hash'), ['cpf_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_professionals_rg_hash'), ['rg_hash'], unique=False)

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_charge_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_charge_mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('auto_charge_flat_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('auto_charge_service_type_rates', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('auto_charge_professional_rates', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('auto_charge_expense_destination', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('auto_charge_expense_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('auto_charge_expense_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payroll_fixed_staff', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('payroll_fixed_staff')
        batch_op.drop_column('auto_charge_expense_category_id')
        batch_op.drop_column('auto_charge_expense_description')
        batch_op.drop_column('auto_charge_expense_destination')
        batch_op.drop_column('auto_charge_professional_rates')
        batch_op.drop_column('auto_charge_service_type_rates')
        batch_op.drop_column('auto_charge_flat_amount')
        batch_op.drop_column('auto_charge_mode')
        batch_op.drop_column('auto_charge_enabled')

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professionals_rg_hash'))
        batch_op.drop_index(batch_op.f('ix_professionals_cpf_hash'))
        batch_op.drop_index(batch_op.f('ix_professionals_cpf'))
        batch_op.create_index('ix_professionals_cpf', ['cpf'], unique=False)
        batch_op.drop_column('rg_hash')
        batch_op.drop_column('cpf_hash')

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_families_rg_hash'))
        batch_op.drop_index(batch_op.f('ix_families_cpf_hash'))
        batch_op.drop_index(batch_op.f('ix_families_cpf'))
        batch_op.create_index('ix_families_cpf', ['cpf'], unique=False)
        batch_op.drop_column('cpf_hash')
        batch_op.drop_column('rg_hash')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_attendance_id', type_='foreignkey')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    # ### end Alembic commands ###
